/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algobreizh.views;

import algobreizh.model.Customer;

/**
 *
 * @author user
 */
public class CustomerView extends javax.swing.JPanel {

    /**
     * Creates new form CustomerViews
     */
    public CustomerView(Customer c) {
        initComponents();
        setComponents(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btProfile = new javax.swing.JButton();
        btRDV = new javax.swing.JButton();
        jlCompany = new javax.swing.JLabel();
        jlCity = new javax.swing.JLabel();
        jlPhone = new javax.swing.JLabel();
        jlName = new javax.swing.JLabel();
        jlFirstname = new javax.swing.JLabel();
        jlrdv = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(220, 70));

        btProfile.setText("Voir Profil");
        btProfile.setInheritsPopupMenu(true);
        btProfile.setMaximumSize(new java.awt.Dimension(80, 20));
        btProfile.setMinimumSize(new java.awt.Dimension(80, 20));
        btProfile.setPreferredSize(new java.awt.Dimension(80, 20));

        btRDV.setText("RDV");
        btRDV.setInheritsPopupMenu(true);
        btRDV.setMaximumSize(new java.awt.Dimension(68, 20));
        btRDV.setMinimumSize(new java.awt.Dimension(68, 20));
        btRDV.setPreferredSize(new java.awt.Dimension(68, 20));

        jlCompany.setText("Company");
        jlCompany.setMaximumSize(new java.awt.Dimension(60, 20));
        jlCompany.setMinimumSize(new java.awt.Dimension(60, 20));
        jlCompany.setPreferredSize(new java.awt.Dimension(60, 20));

        jlCity.setText("Ville");
        jlCity.setMaximumSize(new java.awt.Dimension(60, 20));
        jlCity.setMinimumSize(new java.awt.Dimension(60, 20));
        jlCity.setPreferredSize(new java.awt.Dimension(60, 20));

        jlPhone.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlPhone.setText("Tel");
        jlPhone.setMaximumSize(new java.awt.Dimension(68, 20));
        jlPhone.setMinimumSize(new java.awt.Dimension(68, 20));
        jlPhone.setPreferredSize(new java.awt.Dimension(68, 20));

        jlName.setText("Nom");
        jlName.setMaximumSize(new java.awt.Dimension(60, 20));
        jlName.setMinimumSize(new java.awt.Dimension(60, 20));
        jlName.setPreferredSize(new java.awt.Dimension(60, 20));

        jlFirstname.setText("Prénom");
        jlFirstname.setMaximumSize(new java.awt.Dimension(60, 20));
        jlFirstname.setMinimumSize(new java.awt.Dimension(60, 20));
        jlFirstname.setPreferredSize(new java.awt.Dimension(60, 20));

        jlrdv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlrdv.setText("Date der RDV");
        jlrdv.setMaximumSize(new java.awt.Dimension(80, 20));
        jlrdv.setMinimumSize(new java.awt.Dimension(80, 20));
        jlrdv.setPreferredSize(new java.awt.Dimension(80, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jlrdv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCity, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btRDV, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlFirstname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlrdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btProfile;
    private javax.swing.JButton btRDV;
    private javax.swing.JLabel jlCity;
    private javax.swing.JLabel jlCompany;
    private javax.swing.JLabel jlFirstname;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlPhone;
    private javax.swing.JLabel jlrdv;
    // End of variables declaration//GEN-END:variables

    private void setComponents(Customer c) {
        jlCompany.setText(c.getCompany());
        jlCity.setText(c.getCity());
        jlName.setText(c.getName());
        jlFirstname.setText(c.getFirstname());
        jlPhone.setText(String.valueOf(c.getPhone()));
    }
}
