/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algobreizh.views;

import algobreizh.bdd.BddClient;
import algobreizh.model.Customer;
import java.awt.CardLayout;
import java.awt.GridLayout;
import java.util.ArrayList;

public class Customers extends javax.swing.JFrame {

    /**
     * Creates new form Customerss
     */
    public Customers() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        jpClient.setLayout(new GridLayout(0,1));
        jpAgenda.setLayout(new CardLayout());
        
        addAgenda();
        addCustomers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAgenda = new javax.swing.JButton();
        tfMonday = new javax.swing.JTextField();
        tfTuesday = new javax.swing.JTextField();
        tfWednesday = new javax.swing.JTextField();
        tfThursday = new javax.swing.JTextField();
        tfFriday = new javax.swing.JTextField();
        tfSaturday = new javax.swing.JTextField();
        tfCustomers = new javax.swing.JTextField();
        jpAgenda = new javax.swing.JPanel();
        jpClient = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btAgenda.setText("Sem.");
        btAgenda.setPreferredSize(new java.awt.Dimension(75, 25));
        btAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAgendaMouseClicked(evt);
            }
        });

        tfMonday.setEditable(false);
        tfMonday.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfMonday.setText("Lundi");
        tfMonday.setPreferredSize(new java.awt.Dimension(75, 25));

        tfTuesday.setEditable(false);
        tfTuesday.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfTuesday.setText("Mardi");
        tfTuesday.setPreferredSize(new java.awt.Dimension(75, 25));

        tfWednesday.setEditable(false);
        tfWednesday.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfWednesday.setText("Mercredi");
        tfWednesday.setPreferredSize(new java.awt.Dimension(75, 25));

        tfThursday.setEditable(false);
        tfThursday.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfThursday.setText("Jeudi");
        tfThursday.setPreferredSize(new java.awt.Dimension(75, 25));

        tfFriday.setEditable(false);
        tfFriday.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfFriday.setText("Vendredi");
        tfFriday.setPreferredSize(new java.awt.Dimension(75, 25));

        tfSaturday.setEditable(false);
        tfSaturday.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSaturday.setText("Samedi");
        tfSaturday.setPreferredSize(new java.awt.Dimension(75, 25));

        tfCustomers.setEditable(false);
        tfCustomers.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCustomers.setText("Clients");
        tfCustomers.setPreferredSize(new java.awt.Dimension(100, 25));

        jpAgenda.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jpAgendaLayout = new javax.swing.GroupLayout(jpAgenda);
        jpAgenda.setLayout(jpAgendaLayout);
        jpAgendaLayout.setHorizontalGroup(
            jpAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpAgendaLayout.setVerticalGroup(
            jpAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        jpClient.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jpClientLayout = new javax.swing.GroupLayout(jpClient);
        jpClient.setLayout(jpClientLayout);
        jpClientLayout.setHorizontalGroup(
            jpClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpClientLayout.setVerticalGroup(
            jpClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMonday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTuesday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfWednesday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfThursday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFriday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSaturday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(jpClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tfMonday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTuesday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfWednesday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfThursday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFriday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSaturday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAgendaMouseClicked
        if ("Mois".equals(btAgenda.getText())){
            btAgenda.setText("Sem.");
        }
        else {
            btAgenda.setText("Mois");
        }
    }//GEN-LAST:event_btAgendaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgenda;
    private javax.swing.JPanel jpAgenda;
    private javax.swing.JPanel jpClient;
    private javax.swing.JTextField tfCustomers;
    private javax.swing.JTextField tfFriday;
    private javax.swing.JTextField tfMonday;
    private javax.swing.JTextField tfSaturday;
    private javax.swing.JTextField tfThursday;
    private javax.swing.JTextField tfTuesday;
    private javax.swing.JTextField tfWednesday;
    // End of variables declaration//GEN-END:variables

    private void addCustomers() {
        BddClient bddc = new BddClient();
        ArrayList<Customer> customers = bddc.getCustomers();
        for (Customer c : customers){
            CustomerView cv = new CustomerView(c);
            cv.setVisible(true);
            jpClient.add(cv);
        }
        jpClient.setVisible(true);
    }

    private void addAgenda() {
        jpAgenda.add(new Bymonth());
    }
}
